import React, {useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CSS} from './theme.js';
import {PIXEL_CSS} from './pixel-theme.js';
import PixelHall from './PixelHall.jsx';
import {AvatarEditor, PixelAvatar} from './PixelAvatar.jsx';
import {DEFAULT_AVATAR} from './pixel-world.mjs';

function Preview(){
  const [avatar,setAvatar]=useState({...DEFAULT_AVATAR}),[name,setName]=useState('Moj lik'),[entered,setEntered]=useState(false),[count,setCount]=useState(6),[pos,setPos]=useState({x:560,y:585}),[poster,setPoster]=useState(null);
  const hall=useRef(null);
  const topics=['Voda u našem gradu','Učenje kroz eksperiment','Obnovljiva energija','Digitalna pristupačnost','Mikrosvijet oko nas','Grad po mjeri mladih'];
  const height=Math.max(670,Math.ceil(count/4)*230+200);
  const world={event:{id:'local-pixel-preview',name:'Pixel poster klub'},geometry:{width:1120,height},self:{id:'preview-self',name,hand:false},participants:[],booths:Array.from({length:count},(_,i)=>({number:i+1,title:topics[i%topics.length],x:155+(i%4)*270,y:155+Math.floor(i/4)*230}))};
  const active=world.booths.find(b=>Math.abs(b.x-pos.x)<=105&&Math.abs(b.y-pos.y)<=82);
  return <div className="psi"><style>{CSS+PIXEL_CSS+`.psi-preview-wrap{max-width:1180px;margin:auto;padding:24px}.psi-preview-title{display:flex;justify-content:space-between;align-items:center;gap:15px;flex-wrap:wrap;margin-bottom:20px}.psi-preview-title h1{font-size:26px}.psi-preview-grid{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:20px}.psi-preview-entry{max-width:720px;margin:auto;padding:26px;background:#313d51;border:2px solid #526176}.psi-preview-words{display:grid;gap:8px;margin-top:14px}.psi-preview-words button{text-align:left;font-size:12px}.psi-preview-poster{padding:28px;background:#f8efdb;color:#334f51;margin:16px 0}.psi-preview-poster h2{font-size:23px;color:#334f51}.psi-preview-status{font-size:12px;color:#c4cbbf;margin:8px 0 15px}@media(max-width:800px){.psi-preview-grid{grid-template-columns:1fr}.psi-preview-wrap{padding:12px}.psi-preview-entry{padding:18px}}`}</style><main className="psi-preview-wrap"><header className="psi-preview-title"><div><div className="psi-tag">PSI / LOKALNI PREGLED</div><h1>Poster klub</h1></div><span className="psi-badge">Pregled izgleda i kretanja</span></header>{!entered?<form className="psi-preview-entry" onSubmit={e=>{e.preventDefault();setPos({x:560,y:height-85});setEntered(true)}}><h2>Napravi svog lika</h2><label>Ime u sali<input value={name} onChange={e=>setName(e.target.value)} maxLength={40} required/></label><AvatarEditor value={avatar} onChange={setAvatar}/><label>Broj postera<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[6,12,24].map(n=><option key={n} value={n}>{n}</option>)}</select></label><p className="psi-preview-status">Samostalni probni prikaz. Nije povezan sa salom, drugim učesnicima ili mikrofonom.</p><button className="psi-primary psi-wide" disabled={!name.trim()}>Uđi i prošetaj</button></form>:<><div className="psi-toolbar" style={{marginBottom:18}}><span className="psi-avatar-toolbar"><PixelAvatar avatar={avatar} size={24}/>{name}</span><button onClick={()=>{hall.current?.stop();setEntered(false);setPoster(null)}}>Moj lik</button></div><div className="psi-preview-grid"><div><PixelHall ref={hall} world={world} position={pos} avatar={avatar} onMove={setPos} onInteract={()=>active&&setPoster(active)} disabled={Boolean(poster)}/>{poster&&<section className="psi-preview-poster"><div className="psi-tag">FIKTIVAN PRIMJER / {String(poster.number).padStart(2,'0')}</div><h2>{poster.title}</h2><p>U povezanoj PSI sali ovdje se otvara PDF ili slika istraživačkog postera, uz pitanja učesnika.</p><button onClick={()=>setPoster(null)}>Vrati se u salu</button></section>}</div><aside><h2>Posteri</h2><p className="psi-preview-status">Klik pokreće hodanje do štanda.</p><div className="psi-preview-words">{world.booths.map(b=><button key={b.number} disabled={Boolean(poster)} onClick={()=>hall.current?.walkTo(b.x,b.y+35)}>{String(b.number).padStart(2,'0')} · {b.title}</button>)}</div></aside></div></>}</main></div>
}
createRoot(document.getElementById('psi-pixel-preview')).render(<Preview/>);
